name = "astral"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3ecdc17fc315277cfc82a237d87ce8aca7c2abf6c858ec97bdf883c9bb99a07"

[versions]
fabric = "0.14.22"
minecraft = "1.18.2"
