name = "Create: Astral [Modified]"
author = "Beckkake"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0ac0684b62b1996803cd3672b35125619729bacba2209e487204cdcee62bfee"

[versions]
fabric = "0.14.22"
minecraft = "1.18.2"
