name = "astral"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea922a962acda39b3e1ca85e976e783ba3a2f009e062a752dc46f4319b742896"

[versions]
fabric = "0.14.22"
minecraft = "1.18.2"
