name = "astral"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4685518f125d15fd36afb72e40d29e2cf8039704885ffd74a564fa10cb0f17db"

[versions]
fabric = "0.14.22"
minecraft = "1.18.2"
