name = "astral"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23374a8fdc62416a531c6ad922e4a8b82be5e97f05d54a98d8825ec1ec6530ab"

[versions]
fabric = "0.14.22"
minecraft = "1.18.2"
